# Generated by Django 4.0.2 on 2022-02-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('name', models.TextField()),
                ('text', models.TextField()),
                ('images1', models.ImageField(upload_to='images/')),
                ('name1', models.TextField()),
                ('text1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=250)),
                ('clinet', models.CharField(max_length=250)),
                ('project', models.CharField(max_length=250)),
                ('project_url', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('telegram', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('fecebook', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
            ],
        ),
    ]
