# Generated by Django 4.0.2 on 2022-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='text',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
